
const data = [
  {
    id: 1,
    image: './images/products/product-1.jpeg',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 10,
  },
  {
    id: 1,
    image: './images/products/product-2.jpeg',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 10,
  },
  {
    id: 1,
    image: './images/products/product-3.jpeg',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 10,
  },
  {
    id: 1,
    image: './images/products/product-4.jpeg',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 10,
  },
  {
    id: 1,
    image: './images/products/product-5.jpeg',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 10,
  },
  {
    id: 1,
    image: './images/products/product-6.jpeg',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 10,
  },
  {
    id: 1,
    image: './images/products/product-7.jpeg',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 10,
  },
  {
    id: 1,
    image: './images/products/product-8.jpeg',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 10,
  },
  {
    id: 1,
    image: './images/products/product-9.jpeg',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 10,
  },
  {
    id: 1,
    image: './images/products/product-10.jpeg',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 10,
  },
  {
    id: 1,
    image: './images/products/product-11.jpeg',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 10,
  },
  {
    id: 1,
    image: './images/products/product-12.jpeg',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 10,
  },
  {
    id: 1,
    image: './images/products/product-13.jpeg',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 10,
  },
  {
    id: 1,
    image: './images/products/product-14.jpeg',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 10,
  },
  {
    id: 1,
    image: './images/products/product-15.jpeg',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 10,
  },
  {
    id: 1,
    image: './images/products/product-16.jpeg',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 10,
  },
]

export default data
