import { v4 as uuidv4 } from 'uuid'

const data = [
  {
    id: uuidv4(),
    image: 'https://canifa.com/img/486/733/resize/1/t/1ts22w010-sm053-2-thumb.webp',
    title: 'T- Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 20,
  },
  {
    id: uuidv4(),
    image: 'https://canifa.com/img/486/733/resize/1/t/1ts22w010-sm053-2-thumb.webp',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 10,
  },
  {
    id: uuidv4(),
    image: 'https://canifa.com/img/486/733/resize/2/t/2tl22w042-sr019-1-thumb.webp',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 10,
  },
  {
    id: uuidv4(),
    image: 'https://canifa.com/img/486/733/resize/2/t/2tl22w042-sr019-1-thumb.webp',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 10,
  },
  {
    id: uuidv4(),
    image: 'https://canifa.com/ao-phong-be-trai-dai-tay-2tl22w042',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 10,
  },
  {
    id: uuidv4(),
    image: './images/products/product-6.jpeg',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 10,
  },
  {
    id: uuidv4(),
    image: './images/products/product-7.jpeg',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 10,
  },
  {
    id: uuidv4(),
    image: './images/products/product-8.jpeg',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 10,
  },
  {
    id: uuidv4(),
    image: './images/products/product-9.jpeg',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 10,
  },
  {
    id: uuidv4(),
    image: './images/products/product-10.jpeg',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 10,
  },
  {
    id: uuidv4(),
    image: './images/products/product-11.jpeg',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 10,
  },
  {
    id: uuidv4(),
    image: './images/products/product-12.jpeg',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 10,
  },
  {
    id: uuidv4(),
    image: './images/products/product-13.jpeg',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 10,
  },
  {
    id: uuidv4(),
    image: './images/products/product-14.jpeg',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 10,
  },
  {
    id: uuidv4(),
    image: './images/products/product-15.jpeg',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 10,
  },
  {
    id: uuidv4(),
    image: './images/products/product-16.jpeg',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    price: 10,
  },
]

export default data