
const data = [
  {
    id: 1,
    image: 'https://canifa.com/img/486/733/resize/1/t/1ts22w010-sm053-2-thumb.webp',
    title: 'T- Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    href: '#',
    price: 20,
  },
  {
    id: 2,
    image: 'https://canifa.com/img/486/733/resize/1/t/1ts22w010-sm053-2-thumb.webp',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    href: '#',
    price: 10,
  },
  {
    id: 3,
    image: 'https://canifa.com/img/486/733/resize/2/t/2tl22w042-sr019-1-thumb.webp',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    href: '#',
    price: 10,
  },
  {
    id: 4,
    image: 'https://canifa.com/img/486/733/resize/2/t/2tl22w042-sr019-1-thumb.webp',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    href: '#',
    price: 10,
  },
  {
    id: 5,
    image: 'https://canifa.com/img/486/733/resize/1/t/1ts22w010-sm053-2-thumb.webp',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    href: '#',
    price: 10,
  },
  {
    id: 6,
    image: 'https://canifa.com/img/486/733/resize/1/t/1ts22w010-sm053-2-thumb.webp',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    href: '#',
    price: 10,
  },
  {
    id: 7,
    image: 'https://canifa.com/img/486/733/resize/1/t/1ts22w010-sm053-2-thumb.webp',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    href: '#',
    price: 10,
  },
  {
    id: 8,
    image: 'https://canifa.com/img/486/733/resize/1/t/1ts22w010-sm053-2-thumb.webp',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    href: '#',
    price: 10,
  },
  {
    id: 9,
    image: 'https://canifa.com/img/486/733/resize/1/t/1ts22w010-sm053-2-thumb.webp',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    href: '#',
    price: 10,
  },
  {
    id: 10,
    image: 'https://canifa.com/img/486/733/resize/1/t/1ts22w010-sm053-2-thumb.webp',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    href: '#',
    price: 10,
  },
  {
    id: 11,
    image: 'https://canifa.com/img/486/733/resize/1/t/1ts22w010-sm053-2-thumb.webp',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    href: '#',
    price: 10,
  },
  {
    id: 12,
    image: 'https://canifa.com/img/486/733/resize/1/t/1ts22w010-sm053-2-thumb.webp',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    href: '#',
    price: 10,
  },
  {
    id: 13,
    image: 'https://canifa.com/img/486/733/resize/1/t/1ts22w010-sm053-2-thumb.webp',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    href: '#',
    price: 10,
  },
  {
    id: 14,
    image: 'https://canifa.com/img/486/733/resize/1/t/1ts22w010-sm053-2-thumb.webp',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    href: '#',
    price: 10,
  },
  {
    id: 15,
    image: 'https://canifa.com/img/486/733/resize/1/t/1ts22w010-sm053-2-thumb.webp',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    href: '#',
    price: 10,
  },
  {
    id: 16,
    image: 'https://canifa.com/img/486/733/resize/1/t/1ts22w010-sm053-2-thumb.webp',
    title: 'Shirt',
    desc: 'Lorem ipsum dolor sit amet consectetur adipiscing elit.',
    category: 'Torso',
    type: 'Casual',
    href: '#',
    price: 10,
  },
]

export default data
function uuidv4() {
  throw new Error("Function not implemented.")
}

